# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lookup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lookup.proto',
  package='lookup',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0clookup.proto\x12\x06lookup\"!\n\x0cMatchRequest\x12\x11\n\x05point\x18\x01 \x03(\x02\x42\x02\x10\x01\"\'\n\rMatchResponse\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x05\n\x03_id2@\n\x06Lookup\x12\x36\n\x05Match\x12\x14.lookup.MatchRequest\x1a\x15.lookup.MatchResponse\"\x00\x62\x06proto3'
)




_MATCHREQUEST = _descriptor.Descriptor(
  name='MatchRequest',
  full_name='lookup.MatchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='lookup.MatchRequest.point', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=57,
)


_MATCHRESPONSE = _descriptor.Descriptor(
  name='MatchResponse',
  full_name='lookup.MatchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='lookup.MatchResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_id', full_name='lookup.MatchResponse._id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=59,
  serialized_end=98,
)

_MATCHRESPONSE.oneofs_by_name['_id'].fields.append(
  _MATCHRESPONSE.fields_by_name['id'])
_MATCHRESPONSE.fields_by_name['id'].containing_oneof = _MATCHRESPONSE.oneofs_by_name['_id']
DESCRIPTOR.message_types_by_name['MatchRequest'] = _MATCHREQUEST
DESCRIPTOR.message_types_by_name['MatchResponse'] = _MATCHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MatchRequest = _reflection.GeneratedProtocolMessageType('MatchRequest', (_message.Message,), {
  'DESCRIPTOR' : _MATCHREQUEST,
  '__module__' : 'lookup_pb2'
  # @@protoc_insertion_point(class_scope:lookup.MatchRequest)
  })
_sym_db.RegisterMessage(MatchRequest)

MatchResponse = _reflection.GeneratedProtocolMessageType('MatchResponse', (_message.Message,), {
  'DESCRIPTOR' : _MATCHRESPONSE,
  '__module__' : 'lookup_pb2'
  # @@protoc_insertion_point(class_scope:lookup.MatchResponse)
  })
_sym_db.RegisterMessage(MatchResponse)


_MATCHREQUEST.fields_by_name['point']._options = None

_LOOKUP = _descriptor.ServiceDescriptor(
  name='Lookup',
  full_name='lookup.Lookup',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=100,
  serialized_end=164,
  methods=[
  _descriptor.MethodDescriptor(
    name='Match',
    full_name='lookup.Lookup.Match',
    index=0,
    containing_service=None,
    input_type=_MATCHREQUEST,
    output_type=_MATCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOOKUP)

DESCRIPTOR.services_by_name['Lookup'] = _LOOKUP

# @@protoc_insertion_point(module_scope)
